name: tag
on:
  push:
    branches:
    - main
    paths:
    - source/**
  workflow_dispatch:
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Install xmllint
      run: sudo apt install libxml2-utils
    - uses: actions/checkout@v3
      with:
        ssh-key: "${{ secrets.COMMIT_KEY }}"
    - name: Set the version
      run: |
        prefix="$(echo "cat /Project/PropertyGroup/VersionPrefix/text()" | xmllint --nocdata --shell ./source/FluentErrors/FluentErrors.csproj | sed '1d;$d')"
        suffix="${{ format('pre.{0}', github.run_number) }}"
        echo "VERSION=v${prefix:-1.0.0}-$suffix" >> $GITHUB_ENV
    - name: Create tag
      run: |
        git tag ${{ env.VERSION }}
        git push origin ${{ env.VERSION }}